services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: forohub-app
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: 172.30.0.2
    ports:
      - "8080:8080"
    networks:
      - forohub-network

  mysql:
    image: mysql:8.0
    container_name: forohub-mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 60s
    networks:
      forohub-network:
        ipv4_address: 172.30.0.2

networks:
  forohub-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  mysql_data:
